name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  credentials-json:
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CREDENTIALS_JSON: ${{ inputs.credentials-json }}
  args:
   - /usr/src/app/sync_google_form.mjs
