name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  credentials-json:
    required: true
  form-id:
    required: true
  processed-csv:
    required: true
  extra-args:
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CREDENTIALS_JSON: ${{ inputs.credentials-json }}
    FORM_ID: ${{ inputs.form-id }}
    PROCESSED_CSV: ${{ inputs.processed-csv }}
  args:
   - /usr/src/app/download_google_form_responses.mjs
   - ${{ inputs.extra-args }}
